<%@ Page Title="Manage" MasterPageFile="~/Site.master" Language="C#" AutoEventWireup="true" CodeFile="Manage.aspx.cs" Inherits="Cryptoexch.Manage" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="asp" %>

<%@ Register TagPrefix="custom" Namespace="Cryptoexch" %>

<asp:Content ID="Content" ContentPlaceHolderID="MainContentAdmin" runat="Server">
    <div class="container" id="main-content">
        <div class="col">
            <h4>Employees</h4>
            <asp:Panel ID="Wrapper" runat="server" DefaultButton="btnInsert">
                <custom:GridViewExtended ID="gvEmployee" runat="server"
                    AutoGenerateColumns="false" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true"
                    ShowFooter="True" PageSize="10" AllowPaging="true" CellPadding="4" ForeColor="#333333" GridLines="None"
                    ItemType="Cryptoexch.Models.Employee" DataKeyNames="ID"
                    SelectMethod="GvEmployee_GetData" DeleteMethod="GvEmployee_DeleteItem" UpdateMethod="GvEmployee_UpdateItem" ShowFooterWhenEmpty="true">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>

                        <%--EmploymentDate--%>
                        <asp:TemplateField HeaderText="Employment Date" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="tbEmploymentDateEdit" runat="server" Text='<%# Bind("EmploymentDate","{0:d}") %>' ValidationGroup="vldEditRecord" />
                                <asp:CalendarExtender ID="calEmploy" runat="server" TargetControlID="tbEmploymentDateEdit" PopupButtonID="tbEmploymentDateEdit" />
                                <asp:RequiredFieldValidator ID="vEmploymentDate" runat="server" ControlToValidate="tbEmploymentDateEdit" Display="None"
                                    ErrorMessage="Employment Date Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldEditRecord" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblEmploymentDate" runat="server" Text='<%# Bind("EmploymentDate","{0:d}") %>' />
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbEmploymentDateNew" runat="server" Style="width: 100px;" ValidationGroup="vldNewRecord" />
                                <asp:CalendarExtender ID="calEmployNew" runat="server" TargetControlID="tbEmploymentDateNew" PopupButtonID="tbEmploymentDateNew" />
                                <asp:RequiredFieldValidator ID="vEmploymentDateNew" runat="server" ControlToValidate="tbEmploymentDateNew" Display="None"
                                    ErrorMessage="Employment Date Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldNewRecord" />
                            </FooterTemplate>
                        </asp:TemplateField>

                        <%-- FirstName --%>
                        <asp:TemplateField HeaderText="First Name" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="tbFirstName" runat="server" Text='<%# Bind("FirstName") %>' ValidationGroup="vldEditRecord" />
                                <asp:RequiredFieldValidator ID="valFirstName" runat="server" ControlToValidate="tbFirstName" Display="None"
                                    ErrorMessage="First Name Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldEditRecord" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblFirstName" runat="server" Text='<%# Bind("FirstName") %>' />
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbFirstNameNew" runat="server" Style="width: 100px;" ValidationGroup="vldNewRecord" />
                                <asp:RequiredFieldValidator ID="valFirstNameNew" runat="server" ControlToValidate="tbFirstNameNew" Display="None"
                                    ErrorMessage="First Name Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldNewRecord" />
                            </FooterTemplate>
                        </asp:TemplateField>

                        <%-- LastName --%>
                        <asp:TemplateField HeaderText="Last Name" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="tbLastName" runat="server" Text='<%# Bind("LastName") %>' ValidationGroup="vldEditRecord" />
                                <asp:RequiredFieldValidator ID="valLastName" runat="server" ControlToValidate="tbLastName" Display="None"
                                    ErrorMessage="Last Name Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldEditRecord" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblLastName" runat="server" Text='<%# Bind("LastName") %>' />
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbLastNameNew" runat="server" Style="width: 100px;" ValidationGroup="vldNewRecord" />
                                <asp:RequiredFieldValidator ID="valLastNameNew" runat="server" ControlToValidate="tbLastNameNew" Display="None"
                                    ErrorMessage="Last Name Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldNewRecord" />
                            </FooterTemplate>
                        </asp:TemplateField>

                        <%-- Address --%>
                        <asp:TemplateField HeaderText="Address" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="tbAddress" runat="server" Text='<%# Bind("Address") %>' ValidationGroup="vldEditRecord" />
                                <asp:RequiredFieldValidator ID="valAddress" runat="server" ControlToValidate="tbAddress" Display="None"
                                    ErrorMessage="Address Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldEditRecord" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblAddress" runat="server" Text='<%# Bind("Address") %>' />
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbAddressNew" runat="server" Style="width: 100px;" ValidationGroup="vldNewRecord" />
                                <asp:RequiredFieldValidator ID="valAddressNew" runat="server" ControlToValidate="tbAddressNew" Display="None"
                                    ErrorMessage="Address Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldNewRecord" />
                            </FooterTemplate>
                        </asp:TemplateField>

                        <%-- City --%>
                        <asp:TemplateField HeaderText="City" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="tbCity" runat="server" Text='<%# Bind("City") %>' ValidationGroup="vldEditRecord" />
                                <asp:RequiredFieldValidator ID="valCity" runat="server" ControlToValidate="tbCity" Display="None"
                                    ErrorMessage="City Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldEditRecord" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblCity" runat="server" Text='<%# Bind("City") %>' />
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbCityNew" runat="server" Style="width: 100px;" ValidationGroup="vldNewRecord" />
                                <asp:RequiredFieldValidator ID="valCityNew" runat="server" ControlToValidate="tbCityNew" Display="None"
                                    ErrorMessage="City Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldNewRecord" />
                            </FooterTemplate>
                        </asp:TemplateField>

                        <%-- Email --%>
                        <asp:TemplateField HeaderText="E-mail" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="tbEmail" runat="server" Text='<%# Bind("Email") %>' ValidationGroup="vldEditRecord" />
                                <asp:RequiredFieldValidator ID="valEmail" runat="server" ControlToValidate="tbEmail" Display="None"
                                    ErrorMessage="E-mail Address Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldEditRecord" />
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="tbEmail" SetFocusOnError="true" Display="None"
                                    ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" CssClass="text-danger" ErrorMessage="Bad e-mail address"
                                    ValidationGroup="vldEditRecord" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblEmail" runat="server" Text='<%# Bind("Email") %>' />
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbEmailNew" runat="server" Style="width: 140px;" ValidationGroup="vldNewRecord" />
                                <asp:RequiredFieldValidator ID="valEmailNew" runat="server" ControlToValidate="tbEmailNew" Display="None"
                                    ErrorMessage="E-mail Address Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldNewRecord" />
                                <asp:RegularExpressionValidator runat="server" ControlToValidate="tbEmailNew" SetFocusOnError="true" Display="None"
                                    ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" CssClass="text-danger" ErrorMessage="Bad e-mail address"
                                    ValidationGroup="vldNewRecord" />
                            </FooterTemplate>
                        </asp:TemplateField>

                        <%-- Division --%>
                        <asp:TemplateField HeaderText="Division" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="tbDivision" runat="server" Text='<%# Bind("Division") %>' ValidationGroup="vldEditRecord" />
                                <asp:RequiredFieldValidator ID="valDivision" runat="server" ControlToValidate="tbDivision" Display="None"
                                    ErrorMessage="Division Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldEditRecord" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblDivision" runat="server" Text='<%# Bind("Division") %>' />
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbDivisionNew" runat="server" Style="width: 100px;" ValidationGroup="vldNewRecord" />
                                <asp:RequiredFieldValidator ID="valDivisionNew" runat="server" ControlToValidate="tbDivisionNew" Display="None"
                                    ErrorMessage="Division Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldNewRecord" />
                            </FooterTemplate>
                        </asp:TemplateField>

                        <%-- Title --%>
                        <asp:TemplateField HeaderText="Title" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="tbTitle" runat="server" Text='<%# Bind("Title") %>' ValidationGroup="vldEditRecord" />
                                <asp:RequiredFieldValidator ID="valTitle" runat="server" ControlToValidate="tbTitle" Display="None"
                                    ErrorMessage="Title Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldEditRecord" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblTitle" runat="server" Text='<%# Bind("Title") %>' />
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbTitleNew" runat="server" Style="width: 100px;" ValidationGroup="vldNewRecord" />
                                <asp:RequiredFieldValidator ID="valTitleNew" runat="server" ControlToValidate="tbTitleNew" Display="None"
                                    ErrorMessage="Title Required" ForeColor="Red" SetFocusOnError="True" ValidationGroup="vldNewRecord" />
                            </FooterTemplate>
                        </asp:TemplateField>

                        <%-- TerminationDate --%>
                        <asp:TemplateField HeaderText="Termination Date" HeaderStyle-HorizontalAlign="Left">
                            <EditItemTemplate>
                                <asp:TextBox ID="tbTerminationDateEdit" runat="server" Text='<%# Bind("TerminationDate","{0:d}") %>' ValidationGroup="vldEditRecord" />
                                <asp:CalendarExtender ID="calTerm" runat="server" TargetControlID="tbTerminationDateEdit" PopupButtonID="tbTerminationDateEdit" />
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lblTerminationDate" runat="server" Text='<%# Bind("TerminationDate","{0:d}") %>' />
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbTerminationDateNew" runat="server" Style="width: 100px;" ValidationGroup="vldNewRecord" />
                                <asp:CalendarExtender ID="calTermNew" runat="server" TargetControlID="tbTerminationDateNew" PopupButtonID="tbTerminationDateNew" />
                            </FooterTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <EditRowStyle BackColor="#87aeff" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </custom:GridViewExtended>
                <asp:Button ID="btnInsert" runat="server" Style="display: none;" OnClick="BtnInsert_Click" />
                <asp:ValidationSummary runat="server" ID="valSummaryEdit" ValidationGroup="vldEditRecord" />
                <asp:ValidationSummary runat="server" ID="valSummaryNow" ValidationGroup="vldNewRecord" />
            </asp:Panel>
        </div>
    </div>
</asp:Content>