//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cryptoexch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ClientContext : DbContext
    {
        public ClientContext()
            : base("name=ClientContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CurrencyPair> CurrencyPairs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
    
        [DbFunction("ClientContext", "ClientPortfolioView")]
        public virtual IQueryable<ClientPortfolioView_Result> ClientPortfolioView(string clientID)
        {
            var clientIDParameter = clientID != null ?
                new ObjectParameter("clientID", clientID) :
                new ObjectParameter("clientID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ClientPortfolioView_Result>("[ClientContext].[ClientPortfolioView](@clientID)", clientIDParameter);
        }
    }
}
